# manual execution
trigger: none
pr: none

pool:
  vmImage: 'windows-2019'

stages:
  # A) pack healthcheck
  - stage: healthcheck
    dependsOn: []
    jobs:
      # A1) 
      - job: healthcheck      
        steps:
        - template: azure-templates/healthcheck.yaml
          parameters:
            azureSubscription: '$(PRODUCTION_AZURE_SUBSCRIPTION)'
            appName: '$(PRODUCTION_APP_NAME)'
            endpoint: 'https://$(PRODUCTION_APP_NAME)-staging.azurewebsites.net/healthcheck/ok'
            #endpoint: 'https://httpbin.org/anything'
            headers: 'H1=pippo H2=pluto'
            endpointType: 'private'
            containerInstanceResourceGroup: 'io-d-rg-tdeploy'
            containerInstanceVNet: 'io-d-vnet-tdeploy'
            containerInstanceSubnet: 'azure-devops'
