# manual execution
trigger: none
pr: none

pool:
  vmImage: 'windows-2019'

stages:

  # A) pack healthcheck
  - stage: healthcheck
    dependsOn: []
    jobs:
      # A1) 
      - job: healthcheck      
        steps:
        - template: azure-templates/test-healthcheck.yml
          parameters:
            azureSubscription: '$(PRODUCTION_AZURE_SUBSCRIPTION)'
            resourceGroupName: '$(PRODUCTION_RESOURCE_GROUP_NAME)'
            appName: '$(PRODUCTION_APP_NAME)'
            containerInstanceResourceGroup: "io-d-rg-tdeploy"
            containerInstanceVNet: "io-d-vnet-tdeploy"
