# manual execution
trigger: none
pr: none

pool:
  vmImage: 'windows-2019'

resources:
  repositories:
    - repository: pagopaCommons
      type: github
      name: pagopa/azure-pipeline-templates
      ref: refs/175919444-add-public-request
      endpoint: 'pagopa'

stages:

  # A) pack healthcheck
  - stage: healthcheck
    dependsOn: []
    jobs:
      # A1) 
      - job: healthcheck      
        steps:
        - template: templates/rest-healthcheck/template.yaml@pagopaCommons
          parameters:
            azureSubscription: '$(PRODUCTION_AZURE_SUBSCRIPTION)'
            appName: '$(PRODUCTION_APP_NAME)'
            endpoint: 'https://$(PRODUCTION_APP_NAME)-staging.azurewebsites.net/healthcheck/ok'
            endpointType: 'public'
            containerInstanceResourceGroup: 'io-d-rg-tdeploy'
            containerInstanceVNet: 'io-d-vnet-tdeploy'
            containerInstanceSubnet: 'azure-devops'
