# Azure DevOps pipeline to release a new version and deploy to production.

variables:
  - name: 'NODE_VERSION'
    value: 10.14.1'
  - name: 'YARN_CACHE_FOLDER'
    value: '$(Pipeline.Workspace)/.yarn'
  - name: 'PRODUCTION_APPS'
    readonly: true
    type: object
    value:
      fns3_app1:
        appname: io-d-fn3-tdeploy
        rg: io-d-rg-tdeploy
      fns3_app2:
        appname: io-d-fn3-tdeploy2
        rg: io-d-rg-tdeploy

parameters:
  - name: 'RELEASE_SEMVER'
    displayName: 'When packing a release, define the version bump to apply'
    type: string
    values:
      - major
      - minor
      - patch
    default: minor

# Only manual activations are intended
trigger: none
pr: none

# This pipeline has been implemented to be run on hosted agent pools based both
# on 'windows' and 'ubuntu' virtual machine images and using the scripts defined
# in the package.json file. Since we are deploying on Azure functions on Windows
# runtime, the pipeline is currently configured to use a Windows hosted image for
# the build and deploy.
pool:
  vmImage: 'windows-2019'

resources:
  repositories:
    - repository: pagopaCommons
      type: github
      name: pagopa/azure-pipeline-templates
      ref: refs/tags/v4
      endpoint: 'pagopa'

stages:

  # Create a relase
  # Activated when ONE OF these are met:
  # - is on branch master 
  # - is a tag in the form v{version}-RELEASE
  - stage: Release
    condition:
      and(
        succeeded(),
        or(
          eq(variables['Build.SourceBranch'], 'refs/heads/master'),
          and(
            startsWith(variables['Build.SourceBranch'], 'refs/tags'),
            endsWith(variables['Build.SourceBranch'], '-RELEASE')
          )
        )
      )
    pool:
      vmImage: 'ubuntu-latest'
    jobs:
      - job: make_release
        steps:
        - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
          - template: templates/node-github-release/template.yaml@pagopaCommons 
            parameters:
              semver: '${{ parameters.RELEASE_SEMVER }}'
              gitEmail: $(GIT_EMAIL)
              gitUsername: $(GIT_USERNAME)
              gitHubConnection: $(GITHUB_CONNECTION)
              nodeVersion: $(NODE_VERSION)
              pkg_cache_version_id: $(CACHE_VERSION_ID)
              pkg_cache_folder: $(YARN_CACHE_FOLDER)

        - ${{ if ne(variables['Build.SourceBranch'], 'refs/heads/master') }}:
          - script: |
              echo "We assume this reference to be a valid release: $(Build.SourceBranch). Therefore, there is no need to bundle a new release."
            displayName: 'Skip release bundle'

  # Prepare Artifact
  - stage: Prepare_artifact
    dependsOn:
      - Release
    jobs:
      - job: 'prepare_artifact'
        steps:
          # Build application
          - template: azure-templates/setup-project.yml
            parameters:
              # On the assumption that this stage is executed only when Relase stage is,
              #  with this parameter we set the reference the deploy script must pull changes from.
              # The branch/tag name is calculated from the source branch
              #  ex: Build.SourceBranch=refs/heads/master --> master
              #  ex: Build.SourceBranch=refs/tags/v1.2.3-RELEASE --> v1.2.3-RELEASE
              gitReference: ${{ replace(replace(variables['Build.SourceBranch'], 'refs/tags/', ''), 'refs/heads/', '') }}
          - script: |
              yarn predeploy
            displayName: 'Build'

          # Install functions extensions
          - task: DotNetCoreCLI@2
            inputs:
              command: "build"
              arguments: "-o bin"   
          # Copy application to  
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)'
              TargetFolder: '$(System.DefaultWorkingDirectory)/bundle'
              Contents: |
                **/*
                !.git/**/*
                !**/*.js.map
                !**/*.ts
                !.vscode/**/*
                !.devops/**/*
                !.prettierrc
                !.gitignore
                !README.md
                !jest.config.js
                !local.settings.json
                !test
                !tsconfig.json
                !tslint.json
                !yarn.lock
                !Dangerfile.js
                !CODEOWNERS
                !__*/**/*
            displayName: 'Copy deploy files'

          - script: |
              ls $(System.DefaultWorkingDirectory)/bundle
            displayName: 'ls System.DefaultWorkingDirectory/bundle'
          - script: |
              ls $(System.DefaultWorkingDirectory)
            displayName: 'ls System.DefaultWorkingDirectory<'
          
          - publish: $(System.DefaultWorkingDirectory)/bundle
            artifact: Bundle

  # Deploy on staging slot
  - ${{ each app in variables.PRODUCTION_APPS }}:
    - stage: Deploy_staging_${{ app.Key }}
      dependsOn:
        - Prepare_artifact
      jobs:
        - job: 'do_deploy_${{ app.Key }}'
          steps:
            - checkout: none
            - download: current
              artifact: Bundle
            
            - script: |
                ls $(Pipeline.Workspace)/Bundle
              displayName: 'ls'
              
            - task: AzureFunctionApp@1  
              inputs:
                azureSubscription: '$(PRODUCTION_AZURE_SUBSCRIPTION)'
                resourceGroupName: '${{ app.Value.rg }}'
                appType: 'functionApp'
                appName: '${{ app.Value.appname }}'
                package: '$(Pipeline.Workspace)/Bundle'
                deploymentMethod: 'auto'
                deployToSlotOrASE: true
                slotName: 'staging'
              displayName: Deploy to ${{ app.Key }} staging slot 

  # Check that the staging instance is healthy
  - ${{ each app in variables.PRODUCTION_APPS }}:
    - stage: Healthcheck_${{ app.Key }}
      dependsOn:
        - Deploy_staging_${{ app.Key }}
      jobs:
        - job: 'do_healthcheck_${{ app.Key }}'       
          steps:  
            - checkout: none
            - template: templates/rest-healthcheck/template.yaml@pagopaCommons 
              parameters:
                azureSubscription: '$(PRODUCTION_AZURE_SUBSCRIPTION)'
                appName: '${{ app.Value.appname }}'
                endpoint: 'https://${{ app.Value.appname }}-staging.azurewebsites.net/info'
                endpointType: 'private'
                containerInstanceResourceGroup: 'io-d-rg-tdeploy'
                containerInstanceVNet: 'io-d-vnet-tdeploy'
                containerInstanceSubnet: 'azure-devops' 

  # Promote the staging instance to production
  - ${{ each app in variables.PRODUCTION_APPS }}:
    - stage: Swap_to_production_${{ app.Key }}
      dependsOn:
        - ${{ each app2 in variables.PRODUCTION_APPS }}:
          - Healthcheck_${{ app2.Key }} # every healthcheck is good
          - Deploy_staging_${{ app.Key }}
      jobs:
        - job: 'do_deploy_${{ app.Key }}'       
          steps:  
            - checkout: none
            - task: AzureAppServiceManage@0
              inputs:
                azureSubscription: '$(PRODUCTION_AZURE_SUBSCRIPTION)'
                resourceGroupName: '${{ app.Value.rg }}'
                webAppName: '${{ app.Value.appname }}'
                sourceSlot: staging
                swapWithProduction: true
              displayName: Swap with ${{ app.Key }} production slot
