
parameters:
  - name: 'deploySDK'
    type: boolean
    default: False

  - name: 'dependsOn'
    type: object
    default: []

  - name: 'isBranchMaster'
    default:  $[ eq(variables['Build.SourceBranch'], 'refs/heads/master') ]

  - name: 'variableValue'
    type: string

stages:

- stage: Deploy_SDK
  dependsOn: ${{parameters.dependsOn}}
  condition: eq(variables.deploySDK, true)
  jobs:
  - job: B1
    steps:
      - script: echo Hello Stage B!
      - script: echo $(deploySDK) $(isBranchMaster)

- stage: Deploy_SDK_2
  dependsOn: []


  jobs:

    - job: B2
      steps:
      # Create a variable
      - bash: |
          [ "${{parameters.variableValue}}" == "" ] && PKG_NAME='' || PKG_NAME='--package-name ${{parameters.variableValue}}'  
          echo "##vso[task.setvariable variable=myVariable]$PKG_NAME"

      - script: echo Hello ${{ variables.myVariable }}! -> ${{ parameters.variableValue }} !!