
parameters:
  - name: 'deploySDK'
    type: boolean
    default: False

  - name: 'isBranchMaster'
    default:  $[ eq(variables['Build.SourceBranch'], 'refs/heads/master') ]

stages:

- stage: Deploy_SDK
  condition: eq(variables.deploySDK, true)
  jobs:
  - job: B1
    steps:
      - script: echo Hello Stage B!
      - script: echo $(deploySDK) $(isBranchMaster)

- stage: Deploy_SDK_2
  dependsOn: []
  jobs:
  - job: B2
    steps:
      - script: echo Hello Stage C!
        condition: eq(variables.isBranchMaster, false)